title: My personal website
author:
    name: Tianran Zhang
    email: zhangtr@connect.hku.hk
    description: >
    Feel free to contact with me if you want to have consultation or collaboration with me.

theme: minima

plugin:
    - jekyll-feed
    - jekyll-seo-tag
    
minima:
